### ISSUE TITLE
Unit test for setTimeout `should call the given functions in the correct order` is failing intermittently on Android

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/JsRuntimeHost#9]

**Comment by bghgary** [comment]
It seems there is an intermittent crash even without this test, so perhaps the test is unrelated.

<details>

```
cat ./app/build/outputs/androidTest-results/connected/Pixel_API_27(AVD) - 8.1.0/logcat-com.jsruntimehost.unittests.Main-javaScriptTests.txt
03-09 00:16:40.825  3123  3138 I TestRunner: started: javaScriptTests(com.jsruntimehost.unittests.Main)
03-09 00:16:40.838  3123  3138 D JavaScriptCore.Version: 250230.2.1
03-09 00:16:41.137  3123  3140 I JsRuntimeHost: Passed: AbortController should not throw while aborting and correctly trigger callback
03-09 00:16:41.156  3123  3149 D NetworkSecurityConfig: No Network Security Config specified, using platform default
03-09 00:16:41.243  3123  3128 I zygote64: Do partial code cache collection, code=29KB, data=21KB
03-09 00:16:41.246  3123  3128 I zygote64: After code cache collection, code=29KB, data=21KB
03-09 00:16:41.247  3123  3128 I zygote64: Increasing code cache capacity to 128KB
03-09 00:16:41.289  3123  3140 I JsRuntimeHost: Passed: XMLHTTPRequest should have readyState=4 when load ends
03-09 00:16:41.319  3156  3156 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
03-09 00:16:41.320  1674  1674 I /system/bin/tombstoned: received crash request for pid 3123
03-09 00:16:41.321  3156  3156 I crash_dump64: performing dump of process 3123 (target tid = 3145)
03-09 00:16:41.818  1674  1674 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_00
03-09 00:16:41.854  1645  1645 I Zygote  : Process 3123 exited due to signal (6)
03-09 00:16:41.855  1785  1802 W zygote64: kill(-3123, 9) failed: No such process
03-09 00:16:41.855  1785  1802 I zygote64: Successfully killed process cgroup uid 10060 pid 3123 in 0ms
03-09 00:16:41.865  1785  3163 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
03-09 00:16:41.865  1785  3163 W Binder  : java.lang.Throwable
03-09 00:16:41.865  1785  3163 W Binder  : 	at android.os.BinderProxy.transact(Binder.java:752)
03-09 00:16:41.865  1785  3163 W Binder  : 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:160)
03-09 00:16:41.865  1785  3163 W Binder  : 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
03-09 00:16:41.866  3114  3114 D AndroidRuntime: Shutting down VM
03-09 00:16:42.064  3166  3166 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
03-09 00:16:42.118  3166  3166 W app_process: Unexpected CPU variant for X86 using defaults: x86_64
03-09 00:16:42.121  3166  3166 I app_process: The ClassLoaderContext is a special shared library.
03-09 00:16:42.148  3166  3166 D AndroidRuntime: Calling main entry com.android.commands.pm.Pm
03-09 00:16:42.154  3166  3174 W MessageQueue: Handler (android.os.Handler) {f679d91} sending message to a Handler on a dead thread
03-09 00:16:42.154  3166  3174 W MessageQueue: java.lang.IllegalStateException: Handler (android.os.Handler) {f679d91} sending message to a Handler on a dead thread
03-09 00:16:42.154  3166  3174 W MessageQueue: 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:545)
03-09 00:16:42.154  3166  3174 W MessageQueue: 	at android.os.Handler.enqueueMessage(Handler.java:662)
03-09 00:16:42.154  3166  3174 W MessageQueue: 	at android.os.Handler.sendMessageAtTime(Handler.java:631)
03-09 00:16:42.154  3166  3174 W MessageQueue: 	at android.os.Handler.sendMessageDelayed(Handler.java:601)
03-09 00:16:42.154  3166  3174 W MessageQueue: 	at android.os.Handler.post(Handler.java:357)
03-09 00:16:42.154  3166  3174 W MessageQueue: 	at android.os.ResultReceiver$MyResultReceiver.send(ResultReceiver.java:57)
03-09 00:16:42.154  3166  3174 W MessageQueue: 	at com.android.internal.os.IResultReceiver$Stub.onTransact(IResultReceiver.java:58)
03-09 00:16:42.154  3166  3174 W MessageQueue: 	at android.os.Binder.execTransact(Binder.java:697)
03-09 00:16:42.155  3166  3166 I app_process: System.exit called, status: 0
03-09 00:16:42.155  3166  3166 I AndroidRuntime: VM exiting with result code 0.
```

</details>
